on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m pip install coverage
          python -m coverage run -m unittest discover -p "*_test.py"
          python -m coverage report
          cd quaternion
          python -m coverage run -m unittest discover -p "*_unittest.py"
          python -m coverage report
