on: push

jobs:
  polynomial-test:
    runs-on: ubuntu-latest
    steps:
      - run: cd ../..
      - run: python -m pip install coverage
      - run: python -m coverage run -m polynomial_test
      - run: python -m coverage report
