on: push

jobs:
  polynomial-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install coverage
          python -m coverage run
          python -m coverage report
