on: push

jobs:
  polynomial-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run Tests
        run: |
          python -m pip install coverage
          python -m coverage run -m polynomial_test
          python -m coverage report
