on: push

jobs:
  polynomial-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install coverage
      - run: python -m coverage run -m polynomial_test
      - run: python -m coverage report
